version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app-laravel
    restart: always
    tty: true
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /var/www
    volumes:
      - ./:/var/www

  webserver:
    image: nginx:stable
    container_name: webserver
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  db:
    build: docker/postgres
    container_name: database-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - ./docker/dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
